# Generated by Django 3.2.5 on 2022-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('En Stock', 'En Stock'), ('Agotado', 'Agotado')], default='En stock', max_length=10),
        ),
    ]
